# Import lib

In [8]:
import numpy as np

# Creating arrays

In [49]:
arr = [1,2,3,4]
type(arr)

list

In [133]:
arr = np.array([1, 2, 3, 4], dtype="int")
print(arr)

[1 2 3 4]


In [55]:
type(arr)

numpy.ndarray

In [57]:
# zeros array
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
# ones array
ones = np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
# empty array (uninitialized)
empty = np.empty((2, 2))
empty

array([[0., 0.],
       [0., 0.]])

In [67]:
# array of range
arr_range = np.arange(0, 10, 2)
arr_range

array([0, 2, 4, 6, 8])

In [75]:
# array of evenly spaced number
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [77]:
np.full((2,2), 123)

array([[123, 123],
       [123, 123]])

In [79]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [91]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [97]:
print(z.shape)
print(output[1:-1,1:-1].shape)

(3, 3)
(3, 3)


# Copying arrays

In [103]:
a = np.array([1,2,3])
# b = a
b = a.copy()
b[0] = 100
a

array([1, 2, 3])

# Array operations

In [107]:
a = [1,2,3]
b = [4,5,6]
c = a + b #list concatenation
c

[1, 2, 3, 4, 5, 6]

In [111]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2  # [5, 7, 9]
prod_arr = arr1 * arr2  # [4, 10, 18]
print(sum_arr)
print(prod_arr)

[5 7 9]
[ 4 10 18]


# Array Attributes

In [113]:
# dimensions of the array
arr1.shape

(3,)

In [135]:
# type elements in the array
arr.dtype

dtype('int64')

In [177]:
arr = np.array([1,2,3,4,5,6,7,8,9], dtype='int16')
arr.dtype

dtype('int16')

In [139]:
# number of elements in the array
arr.size

5

In [145]:
# number of byte memory of each element
arr.itemsize

8

In [155]:
# number of dimensions
arr.ndim

2

# Reshaping and Transposing

In [179]:
arr_reshaped = arr.reshape((3,3))
arr_reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [181]:
arr_transposed = arr_reshaped.T
arr_transposed

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int16)

# Slicing and Indexing

In [193]:
# Basic slicing
arr = np.array([10,20,30,40,50])
arr[1:3]

array([20, 30])

In [195]:
# Multidimensional slicing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d[1:, :2]

array([[4, 5],
       [7, 8]])

In [197]:
arr_2d[1,1]

5

In [201]:
arr_2d[:, 0]

array([1, 4, 7])

# Broadcasting

In [203]:
arr = np.array([1, 2, 3])
arr_broadcast = arr + 5
arr_broadcast

array([6, 7, 8])

In [205]:
arr_broadcast = arr * 5
arr_broadcast

array([ 5, 10, 15])

In [207]:
# Array with shape (3,)
a = np.array([1, 2, 3])

# Array with shape (3, 1)
b = np.array([[10], [20], [30]])

# Broadcasting adds an extra dimension to 'a' and performs element-wise addition
result = a + b
result

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

# Useful Functions

In [209]:
# sum of elements
arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.sum(arr)

55

In [215]:
np.mean(arr)

5.5

In [217]:
np.std(arr)

2.8722813232690143

In [219]:
np.max(arr)

10

In [221]:
np.min(arr)

1

In [225]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.min(arr_2d, axis=0)

array([1, 2, 3])

# Random numbers

In [261]:
# Random array
np.random.seed(0)
random_arr = np.random.rand(3,3)
random_arr

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [288]:
rand_ints = np.random.randint(0, 10, size=(2,2))
rand_ints

array([[ 4,  9],
       [10, 10]])

# Fancy indexing

In [290]:
arr = np.array([10, 20, 30, 40, 50])
bool_arr = arr > 30
result = arr[bool_arr]
result

array([40, 50])

In [298]:
arr[[True, True, False, False, False]]

array([10, 20])

# Linear algebra

In [300]:
# Dot product
# [1, 2] . [3, 4] = 1 * 3 + 2 * 4
a = np.array([1, 2])
b = np.array([3, 4])
dot_product = np.dot(a, b)
dot_product

11

In [302]:
# Equivalent using @ operator
dot_product = a @ b
dot_product

11

In [304]:
# Matrix multiplication (applies if the dtype is matrix)
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
result = np.dot(mat1, mat2)
result

array([[19, 22],
       [43, 50]])

In [306]:
# Inverse of a matrix
mat = np.array([[1, 2], [3, 4]])
inv_mat = np.linalg.inv(mat)
inv_mat

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [308]:
result = np.dot(mat, inv_mat)
result

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [310]:
np.round(result).astype('int')

array([[1, 0],
       [0, 1]])

In [312]:
# Determinant
det = np.linalg.det(mat)
np.round(det)

-2.0

In [314]:
vals, vecs = np.linalg.eig(mat)
vals, vecs

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [316]:
# Solving systems of linear equations
# this solves the system Ax=b
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

array([2., 3.])

In [318]:
A.dot(x)

array([9., 8.])

In [320]:
np.cos(A)

array([[-0.9899925 ,  0.54030231],
       [ 0.54030231, -0.41614684]])

In [328]:
# dot and matmul is the same for matrix multiplication
a = np.ones((2,4))
print(a)

b = np.full((4,2), 3)
print(b)

np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]]


array([[12., 12.],
       [12., 12.]])